FROM node:20-alpine as build

WORKDIR /app

COPY /frontend/package.json ./
COPY /frontend/package-lock.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /bin/www
COPY /frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
