FROM golang:1.22

EXPOSE 8080
RUN mkdir /usr/local/bin/app
WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

CMD ["/usr/local/bin/app/candywatch"]
